baseURL: https://jvcanavarro.github.io/
title: João V. Canavarro
theme: eureka

paginate: 3
enableEmoji: true
enableGitInfo: true
summaryLength: 75

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false

# googleAnalytics: UA-123-45

markup:
  highlight:
    codeFences: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: always
